name: GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install Rust (rustup)
      run: rustup update stable --no-self-update && rustup default stable

    - name: Build book
      run: cargo --version
